spring.application.name=ecommercecart

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/vgmcart
spring.datasource.username=root
spring.datasource.password=lmao
